#!/bin/bash

ln -sfT .config/dotfiles/inputrc ~/.inputrc
ln -sfT .config/dotfiles/bashrc ~/.bashrc
ln -sfT .config/dotfiles/jshintrc ~/.jshintrc
ln -sfT .config/dotfiles/gitconfig ~/.gitconfig
ln -sfT .config/dotfiles/tmux.conf ~/.tmux.conf
ln -sfT .config/dotfiles/vim ~/.vim
ln -sfT dotfiles/vim ~/.config/nvim

if which >/dev/null vim; then
  vim +PlugInstall +qall
elif which >/dev/null nvim; then
  nvim +PlugInstall +qall
fi
